language: node_js
node_js:
- 4
- 5
- 6
addons:
  # Required to compile native modules on newer Node.js versions
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/117063f9c1031b17e557
    on_start: never
    on_failure: change
deploy:
  provider: npm
  email: hello@mylisabox.com
  api_key:
    secure: TYv9n0VB6I1KVOQG7cc03lg40XVJHgyB4zMCctztTp3Go0nEZmK3lLlstCjvjt0IPu796MIp28Ji5iW22aicUtgKeknGZo13FVtvCaVVzap+vj0Cz8DPpJdmtY4Vx2kRY/p9RtULwN6U1uwZvS835TxeVS4JiPhDoAtacHSh5Hi5sE1DqAo6hatSUovnLXcQUqVItZjzs9xkV220g/9BQFFWwPNHPvHtU9DZmNnjWrey/+m2OPAOladnqG0FuS/g0ZC3mc64P/gG7xkpIxy7duyU2sVby4w4q2WuPrDS1UYZZlhZvUJ8yy5Tx7j22u87RYG2u+goHNkdelzTGeA+pnfwNI1+JhBbldsNs+FxiSGJGzP6KCOji7uIbKAW4IGe96oxNKFfXI/zh1mH/rg9P+18hIEcvksIUGjlPSMjQCx5LzcHnYrnQHU2y7flA//ZgdRrI8r1frgA/vBMHvj81d05rJWckK+JgaSyyGoHDweDFxKWpUfqCKavdsXkeUOEl3RHHW31k072XY9bVUotp48+F3EszAGFQOGugyuBqdzgZTDPzNmyS4t/hBI1gUd6L93uLqKCE7vd2KalVPeTsrLnblR43negvvuFaf8nZcMeVTbwy9uYHuleH0N2kJ1P+zSFdcp3smgTYL3oNU0fuSaIDCP7ZMp/SrItJKJxL2M=
  on:
    tags: true
    repo: mylisabox/lisa-plugin
    node: 6
